[package]
name = "lantern"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.28.5"
env_logger = "0.10.0"
log = "0.4.17"
wgpu = "0.16.0"
egui-wgpu = "0.21.0"
egui-winit = "0.21.1"